"""
Generates contract invariant patches and pull request bodies based on Replay Worker blind spots.
"""
import re
from typing import List, Dict, Any
from collections import defaultdict
from .worker import BlindSpot


class ContractPatcher:
    """Analyzes surviving mutations and suggests YAML invariant additions."""

    @staticmethod
    def suggest_invariants(blind_spots: List[BlindSpot | Dict[str, Any]]) -> Dict[str, List[str]]:
        suggestions: Dict[str, List[str]] = defaultdict(list)

        for spot in blind_spots:
            m_type = spot.mutation_type if isinstance(spot, BlindSpot) else spot.get("mutation_type", "")
            desc = spot.description if isinstance(spot, BlindSpot) else spot.get("description", "")

            if m_type == "FILTER_DROP":
                # Matches: "Drop WHERE clause predicate: status = 'active'" or "Dropped predicate: x"
                match = re.search(r"(?:Drop WHERE clause predicate|Dropped predicate|Drop predicate):\s*(.+)", desc, re.IGNORECASE)
                if match:
                    pred = match.group(1).strip()
                    if pred not in suggestions["population_required"]:
                        suggestions["population_required"].append(pred)
                else:
                    suggestions["population_required"].append(desc)

            elif m_type == "GRAIN_DROP":
                # Matches: "Drop GROUP BY dimension: customer_id"
                match = re.search(r"(?:Drop GROUP BY dimension|Dropped dimension):\s*(.+)", desc, re.IGNORECASE)
                if match:
                    dim = match.group(1).strip()
                    if dim not in suggestions["grain_dimensions"]:
                        suggestions["grain_dimensions"].append(dim)
                else:
                    suggestions["grain_dimensions"].append(desc)

            elif m_type in ("AGGREGATION_SWAP", "MATH_OPERATOR_INVERT"):
                suggestions["aggregation_review_needed"].append(desc)

            elif m_type == "BOUNDARY_SHIFT":
                suggestions["boundary_rules"].append(desc)

        return dict(suggestions)

    @staticmethod
    def generate_pr_body(metric_id: str, suggestions: Dict[str, List[str]], trace_id: str = "") -> str:
        body = f"## 🤖 Automated Contract Patch for `{metric_id}`\n\n"
        body += f"The **Phase 8.2 Replay Worker** detected **Silent Survivors** during offline mutation testing"
        if trace_id:
            body += f" (replaying trace `{trace_id}`).\n\n"
        else:
            body += ".\n\n"
        body += "The following mutations passed the Semantic Firewall but produced empirical metric divergence on historical data, "
        body += "indicating the metric contract is underspecified.\n\n"

        if "population_required" in suggestions and suggestions["population_required"]:
            body += "### Suggested `population.required_filters` Additions:\n```yaml\ninvariants:\n  population:\n    required_filters:\n"
            for pred in suggestions["population_required"]:
                body += f'      - "{pred}"\n'
            body += "```\n\n"

        if "grain_dimensions" in suggestions and suggestions["grain_dimensions"]:
            body += "### Suggested `grain.required_dimensions` Additions:\n```yaml\ninvariants:\n  grain:\n    required_dimensions:\n"
            for dim in suggestions["grain_dimensions"]:
                body += f'      - "{dim}"\n'
            body += "```\n\n"

        if "aggregation_review_needed" in suggestions and suggestions["aggregation_review_needed"]:
            body += "### ⚠️ Aggregation & Arithmetic Invariants to Review:\n"
            for item in suggestions["aggregation_review_needed"]:
                body += f"- {item}\n"
            body += "\n"

        body += "---\n*Generated by SRE Replay Worker | Action: Review and merge into `contracts/` to enforce in Phase 8.1 Firewall.*"
        return body
