# Provenance:
#   Repository: https://github.com/dbt-labs/jaffle_shop
#   Organization: dbt Labs
#   Reference: models/staging/schema.yml, tests/assert_positive_total_for_payments.sql

version: 2
models:
- name: model_net_revenue
  columns:
  - name: customer_id
    tests:
    - not_null
  - name: reporting_month
    tests:
    - not_null
  - name: net_revenue
    tests:
    - not_null
    - accepted_range:
        min_value: 0.0

