# Provenance:
#   Repository: https://github.com/fivetran/dbt_stripe
#   Organization: Fivetran
#   Reference: models/stripe_models.yml

version: 2
models:
- name: model_b2b_saas_arr
  columns:
  - name: customer_id
    tests:
    - not_null
  - name: annual_recurring_revenue
    tests:
    - not_null
    - accepted_range:
        min_value: 0.0

