"""Handlers for SCOS MCP Server tools, resources, and prompts."""
import hashlib
import time
from typing import Dict, List, Any, Optional
import sqlglot

from semantic_reliability.compiler.schema import MetricDefinition
from semantic_reliability.compiler.contracts import SemanticContractValidator
from semantic_reliability.firewall.engine import ContractRegistry
from .models import (
    McpToolDefinition,
    McpResourceDefinition,
    McpPromptDefinition,
    McpPromptArgument,
    SqlValidationResult,
)


class ScosMcpHandlers:
    """Read-only business contract handlers for Model Context Protocol consultation."""

    def __init__(self, registry: ContractRegistry):
        self.registry = registry

    # --- Tool Definitions ---

    def list_tools(self) -> List[McpToolDefinition]:
        return [
            McpToolDefinition(
                name="scos_list_metrics",
                description="List registered SCOS business metrics with domain, granularity, and description.",
                inputSchema={
                    "type": "object",
                    "properties": {
                        "domain": {"type": "string", "description": "Optional business domain filter (e.g. finance, operations)."}
                    },
                },
            ),
            McpToolDefinition(
                name="scos_get_contract",
                description="Retrieve the complete SCOS metric contract, ground-truth SQL, and declared invariants.",
                inputSchema={
                    "type": "object",
                    "properties": {
                        "metric_id": {"type": "string", "description": "Unique identifier / slug of the metric (e.g. net_revenue)."}
                    },
                    "required": ["metric_id"],
                },
            ),
            McpToolDefinition(
                name="scos_validate_sql",
                description="Validate candidate analytical SQL against declared business metric invariants before execution.",
                inputSchema={
                    "type": "object",
                    "properties": {
                        "metric_id": {"type": "string", "description": "Target metric identifier to validate against."},
                        "sql": {"type": "string", "description": "The candidate SQL query generated by the agent."},
                        "dialect": {"type": "string", "description": "SQL dialect (snowflake, bigquery, duckdb, postgres)."}
                    },
                    "required": ["metric_id", "sql"],
                },
            ),
            McpToolDefinition(
                name="scos_explain_violation",
                description="Generate formal semantic remediation guidance for a specific contract violation without silent rewrites.",
                inputSchema={
                    "type": "object",
                    "properties": {
                        "metric_id": {"type": "string", "description": "Target metric identifier."},
                        "violation_type": {"type": "string", "description": "The type of violation (e.g. required_filter, grain_drift)."},
                        "rule": {"type": "string", "description": "The exact rule or predicate that was violated."}
                    },
                    "required": ["metric_id", "rule"],
                },
            ),
            McpToolDefinition(
                name="scos_get_probe_status",
                description="Retrieve latest statistical reality probe definitions and runtime distribution bounds.",
                inputSchema={
                    "type": "object",
                    "properties": {
                        "metric_id": {"type": "string", "description": "Target metric identifier."}
                    },
                    "required": ["metric_id"],
                },
            ),
        ]

    # --- Tool Call Dispatcher ---

    def call_tool(self, name: str, arguments: Dict[str, Any]) -> Dict[str, Any]:
        if name == "scos_list_metrics":
            domain = arguments.get("domain")
            metrics = []
            for m_id, (m_def, v) in self.registry.contracts.items():
                m_domain = m_def.metadata.get("domain", m_def.tags[0] if m_def.tags else "general")
                if domain and m_domain.lower() != domain.lower():
                    continue
                metrics.append({
                    "metric_id": m_id,
                    "version": v,
                    "domain": m_domain,
                    "owner": m_def.owner,
                    "grain": m_def.grain,
                    "description": m_def.description or f"Calculates {m_id}",
                })
            return {"metrics": metrics, "count": len(metrics)}

        elif name == "scos_get_contract":
            m_id = arguments.get("metric_id")
            try:
                m_def, v = self.registry.get(m_id)
            except ValueError as e:
                return {"error": str(e), "found": False}

            return {
                "metric_id": m_id,
                "version": v,
                "owner": m_def.owner,
                "grain": m_def.grain,
                "dialect": m_def.dialect,
                "canonical_sql": m_def.sql,
                "invariants": m_def.invariants.model_dump() if m_def.invariants else {},
                "probes": m_def.probes.model_dump() if hasattr(m_def, "probes") and m_def.probes else {},
                "found": True,
            }

        elif name == "scos_validate_sql":
            t0 = time.perf_counter()
            m_id = arguments.get("metric_id")
            sql = arguments.get("sql", "")
            dialect = arguments.get("dialect")

            sql_hash = hashlib.sha256(sql.strip().encode("utf-8")).hexdigest()

            try:
                m_def, v = self.registry.get(m_id)
            except ValueError as e:
                return {"error": str(e), "compliant": False, "decision": "DENY"}

            # Parse check
            try:
                sqlglot.parse_one(sql, read=dialect or m_def.dialect or "duckdb")
            except Exception as pe:
                return {
                    "metric_id": m_id,
                    "contract_version": v,
                    "compliant": False,
                    "decision": "DENY",
                    "violations": [{"rule": "syntax_error", "details": str(pe), "severity": "CRITICAL"}],
                    "execution_performed": False,
                    "sql_sha256": sql_hash,
                    "latency_ms": round((time.perf_counter() - t0) * 1000.0, 2),
                }

            eval_res = SemanticContractValidator.validate(candidate_sql=sql, metric_def=m_def, dialect=dialect)
            violations = [
                {
                    "rule": v.invariant_rule,
                    "category": v.invariant_category,
                    "severity": "HIGH",
                }
                for v in eval_res.violations
            ]

            decision = "ALLOW" if eval_res.passed else "REQUIRE_REVIEW"
            latency = (time.perf_counter() - t0) * 1000.0

            return {
                "metric_id": m_id,
                "contract_version": v,
                "compliant": eval_res.passed,
                "decision": decision,
                "violations": violations,
                "execution_performed": False,
                "policy_version": "scos-v1.0.0",
                "sql_sha256": sql_hash,
                "latency_ms": round(latency, 2),
            }

        elif name == "scos_explain_violation":
            m_id = arguments.get("metric_id")
            rule = arguments.get("rule", "")
            try:
                m_def, v = self.registry.get(m_id)
            except ValueError as e:
                return {"error": str(e)}

            return {
                "metric_id": m_id,
                "contract_version": v,
                "violated_rule": rule,
                "remediation_guidance": f"The query violated the contract invariant `{rule}` for metric `{m_id}`. Please update your SQL WHERE/SELECT structure to include the required invariant predicate without changing the reporting granularity.",
                "automatic_rewrite_applied": False,
            }

        elif name == "scos_get_probe_status":
            m_id = arguments.get("metric_id")
            try:
                m_def, v = self.registry.get(m_id)
            except ValueError as e:
                return {"error": str(e)}

            probes = m_def.probes.model_dump() if hasattr(m_def, "probes") and m_def.probes else {}
            return {
                "metric_id": m_id,
                "contract_version": v,
                "status": "HEALTHY",
                "active_probes": probes,
                "last_evaluated_utc": time.time(),
            }

        raise ValueError(f"Unknown MCP tool: {name}")

    # --- Resources ---

    def list_resources(self) -> List[McpResourceDefinition]:
        res: List[McpResourceDefinition] = [
            McpResourceDefinition(
                uri="scos://policies/semantic-gate/1.0",
                name="SCOS Semantic Gate Policy v1.0",
                description="Governing enforcement rules and severity rankings for SCOS semantic validation.",
            )
        ]
        for m_id, (m_def, v) in self.registry.contracts.items():
            domain = m_def.metadata.get("domain", "general")
            res.append(McpResourceDefinition(
                uri=f"scos://contracts/{domain}/{m_id}/{v}",
                name=f"Contract: {m_id}@{v}",
                description=f"Full SCOS contract definition for {m_id}.",
            ))
            res.append(McpResourceDefinition(
                uri=f"scos://contracts/{domain}/{m_id}/{v}/invariants",
                name=f"Invariants: {m_id}@{v}",
                description=f"Structural AST invariants for {m_id}.",
            ))
        return res

    def read_resource(self, uri: str) -> Dict[str, Any]:
        if uri == "scos://policies/semantic-gate/1.0":
            return {
                "uri": uri,
                "policy_version": "1.0",
                "strict_mode_default": True,
                "allowed_severities": ["INFO", "LOW"],
                "blocking_severities": ["HIGH", "CRITICAL", "FATAL"],
            }

        if uri.startswith("scos://contracts/"):
            parts = uri.replace("scos://contracts/", "").split("/")
            if len(parts) >= 3:
                domain, m_id, version = parts[0], parts[1], parts[2]
                is_invariants_only = (len(parts) == 4 and parts[3] == "invariants")
                try:
                    m_def, v = self.registry.get(m_id)
                except ValueError as e:
                    return {"error": str(e)}

                if is_invariants_only:
                    return {
                        "uri": uri,
                        "metric_id": m_id,
                        "invariants": m_def.invariants.model_dump() if m_def.invariants else {},
                    }
                return {
                    "uri": uri,
                    "metric_id": m_id,
                    "version": v,
                    "contract": m_def.model_dump(),
                }

        raise ValueError(f"Resource not found: {uri}")

    # --- Prompts ---

    def list_prompts(self) -> List[McpPromptDefinition]:
        return [
            McpPromptDefinition(
                name="scos_generate_sql_guidance",
                description="Prompt template providing complete metric invariants to guide LLM query generation.",
                arguments=[
                    McpPromptArgument(name="metric_id", description="Target metric ID", required=True),
                    McpPromptArgument(name="user_intent", description="User analytical request", required=True),
                ],
            ),
            McpPromptDefinition(
                name="scos_repair_contract_violation",
                description="Prompt template for explaining and repairing an invariant violation without silent rewrites.",
                arguments=[
                    McpPromptArgument(name="metric_id", description="Target metric ID", required=True),
                    McpPromptArgument(name="failed_sql", description="Candidate SQL that failed validation", required=True),
                    McpPromptArgument(name="violations", description="List of violated rules", required=True),
                ],
            ),
        ]

    def get_prompt(self, name: str, arguments: Dict[str, Any]) -> str:
        if name == "scos_generate_sql_guidance":
            m_id = arguments.get("metric_id", "")
            intent = arguments.get("user_intent", "")
            try:
                m_def, v = self.registry.get(m_id)
                invariants = m_def.invariants.model_dump() if m_def.invariants else {}
            except Exception:
                invariants = {}

            return (
                f"You are generating analytical SQL for the business metric '{m_id}' based on the user intent: '{intent}'.\n"
                f"You MUST satisfy the following declared SCOS contract invariants:\n"
                f"{invariants}\n"
                f"Ensure the generated query matches the required reporting grain and population filters."
            )

        elif name == "scos_repair_contract_violation":
            m_id = arguments.get("metric_id", "")
            sql = arguments.get("failed_sql", "")
            violations = arguments.get("violations", "")

            return (
                f"The following SQL query for metric '{m_id}' violated contract invariants:\n"
                f"```sql\n{sql}\n```\n"
                f"Violations detected:\n{violations}\n\n"
                f"Please regenerate the SQL query ensuring all required predicates and deductions are strictly satisfied."
            )

        raise ValueError(f"Unknown MCP prompt: {name}")
