# Provenance:
#   Repository: https://github.com/tuva-health/tuva
#   Organization: Tuva Health
#   Reference: models/data_marts/readmissions/schema.yml

version: 2
models:
- name: model_hospital_readmission_rate
  columns:
  - name: department
    tests:
    - not_null
  - name: readmission_rate
    tests:
    - not_null
    - accepted_range:
        min_value: 0.0
        max_value: 1.0

